<a href="https://colab.research.google.com/github/sumanthgm/Maths_Foundation/blob/main/practice_MF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import scipy.linalg as la

Numpy array can be used to create a vector - both row and column vectors.

In [10]:
a= np.array([1,2,3,4,5]) #6 dimention vector
a

array([1, 2, 3, 4, 5])

The shape and type of the vectors can be checked using array_name.shape and type(array_name)

In [14]:
a.shape

(5,)

Data type

In [19]:
type(a)
a.dtype

dtype('int64')

In [30]:
a.shape=(1,5)
print(a)

[[1 2 3 4 5]]


In [31]:
a.transpose()

array([[1],
       [2],
       [3],
       [4],
       [5]])

Addition & Subtraction  Vectors & Multiplication

In [33]:
a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


### Matrix Creation and manipulation

In [36]:
# Create a matrix with all zeros
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [37]:
# Create a matrix with all ones
a=np.ones((3,1))
a

array([[1.],
       [1.],
       [1.]])

In [43]:
# Create matrix with floting numbers
a=np.full((1,3),1.1)
a

array([[1.1, 1.1, 1.1]])

In [56]:
# Creat random numbers
a=np.random.random((3,3))
a


array([[0.31776355, 0.74476711, 0.49943758],
       [0.80083456, 0.73639878, 0.76707205],
       [0.16827801, 0.57501556, 0.23452609]])

# Vector and Matrix Operations